name: spacex_capsules
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^4.0.4
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0
  equatable: ^1.0.1
  rxdart: ^0.23.1
  logger: 0.9.1
  data_connection_checker: ^0.3.4
  http: ^0.12.0+3
  dartz: ^0.8.9
  shared_preferences: ^0.5.6
  json_annotation: ^3.0.0
  dio: 3.0.9
  retrofit: 1.3.4
  cached_network_image: ^2.2.0+1
  simple_search_bar: ^0.1.7
  floor: ^0.13.0
  sqflite: ^1.3.1
  flutter_localizations:
    sdk: flutter
  connectivity: ^0.4.8+6  
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

